{
    imports = [
        ./anglebracket.nix
        ./bleedingedge.nix
        ./cli
        ./clipboard.nix
        ./desktop
        ./fixes
        ./fonts.nix
        ./gaming.nix
        ./git.nix
        ./gnunet.nix
        ./greetd.nix
        ./grub.nix
        ./keymap.nix
        ./laptop-utils.nix
        ./man.nix
        ./ncmpcpp.nix
        ./networkmanager.nix
        ./nix.nix
        ./ntfs.nix
        ./printing.nix
        ./sound.nix
        ./ssh.nix
        ./users
        ./video.nix
        ./vm.nix
        ./wireless
        ./xdg.nix
    ];
}
