# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:
{
    imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems = {
        "/" = {
            device = "/dev/disk/by-uuid/adf68f11-1bd1-422c-ae4e-28366e9621b5";
            fsType = "ext4";
        };
        "/boot" = {
            #device = "/dev/disk/by-uuid/4F05-A38C";
            device = "/dev/disk/by-uuid/0854-02D5";
            fsType = "vfat";
        };
        "/home" = {
            device = "/dev/disk/by-uuid/088797eb-cb69-44ef-9be6-1cc215f04eb6";
            fsType = "ext4";
        };
        "/mnt/ssd2" = {
            device = "/dev/disk/by-uuid/20b0c6dc-a6a3-4d1c-bf31-4fdedec1e294";
            fsType = "ext4";
        };
    };

    swapDevices = [
        { device = "/dev/disk/by-uuid/c5315dfe-ce29-4d3a-96ff-cdbc00b81eb0"; }
    ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
